### ISSUE TITLE
about the fw compline

### ISSUE THREAD

**Issue by yofizane** [yaqwsx/DrLCD#2]
hello,I use vscode&platforminIO,set "default_envs = STM32F103RC_btt" to comoline the fw,but it failed to compline,it shows as below,may I know how I can  solove that？

Compiling .pio\build\STM32F103RC_btt\src\src\gcode\control\M108_M112_M410.cpp.o
In file included from Marlin\src\feature\drlcd\drlcd.h:6,
                 from Marlin\src\feature\drlcd\drlcd.cpp:1:
.pio\libdeps\STM32F103RC_btt\Adafruit TSL2561/Adafruit_TSL2561_U.h:170:21: warning: 'boolean' is deprecated [-Wdeprecated-declarations]
  170 |   boolean begin(void);
      |                     ^
In file included from C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/wiring.h:34,
                 from C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/Arduino.h:36,
                 from C:\Users\Admin\.platformio\packages\framework-arduinoststm32\libraries\Wire\src/Wire.h:26,
                 from Marlin\src\feature\drlcd\drlcd.h:4,
                 from Marlin\src\feature\drlcd\drlcd.cpp:1:
C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/wiring_constants.h:110:14: note: declared here
  110 | typedef bool boolean __attribute__((deprecated));
      |              ^~~~~~~
In file included from Marlin\src\feature\drlcd\drlcd.h:6,
                 from Marlin\src\feature\drlcd\drlcd.cpp:1:
.pio\libdeps\STM32F103RC_btt\Adafruit TSL2561/Adafruit_TSL2561_U.h:171:33: warning: 'boolean' is deprecated [-Wdeprecated-declarations]
  171 |   boolean begin(TwoWire *theWire);
      |                                 ^
In file included from C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/wiring.h:34,
                 from C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/Arduino.h:36,
                 from C:\Users\Admin\.platformio\packages\framework-arduinoststm32\libraries\Wire\src/Wire.h:26,
                 from Marlin\src\feature\drlcd\drlcd.h:4,
                 from Marlin\src\feature\drlcd\drlcd.cpp:1:
C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/wiring_constants.h:110:14: note: declared here
  110 | typedef bool boolean __attribute__((deprecated));
      |              ^~~~~~~
In file included from Marlin\src\feature\drlcd\drlcd.h:6,
                 from Marlin\src\feature\drlcd\drlcd.cpp:1:
.pio\libdeps\STM32F103RC_btt\Adafruit TSL2561/Adafruit_TSL2561_U.h:172:16: warning: 'boolean' is deprecated [-Wdeprecated-declarations]
  172 |   boolean init();
      |                ^
In file included from C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/wiring.h:34,
                 from C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/Arduino.h:36,
                 from C:\Users\Admin\.platformio\packages\framework-arduinoststm32\libraries\Wire\src/Wire.h:26,
                 from Marlin\src\feature\drlcd\drlcd.h:4,
                 from Marlin\src\feature\drlcd\drlcd.cpp:1:
C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/wiring_constants.h:110:14: note: declared here
  110 | typedef bool boolean __attribute__((deprecated));
      |              ^~~~~~~
In file included from Marlin\src\feature\drlcd\drlcd.h:6,
                 from Marlin\src\feature\drlcd\drlcd.cpp:1:
.pio\libdeps\STM32F103RC_btt\Adafruit TSL2561/Adafruit_TSL2561_U.h:189:11: warning: 'boolean' is deprecated [-Wdeprecated-declarations]
  189 |   boolean _tsl2561Initialised;
      |           ^~~~~~~~~~~~~~~~~~~
In file included from C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/wiring.h:34,
                 from C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/Arduino.h:36,
                 from C:\Users\Admin\.platformio\packages\framework-arduinoststm32\libraries\Wire\src/Wire.h:26,
                 from Marlin\src\feature\drlcd\drlcd.h:4,
                 from Marlin\src\feature\drlcd\drlcd.cpp:1:
C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/wiring_constants.h:110:14: note: declared here
  110 | typedef bool boolean __attribute__((deprecated));
      |              ^~~~~~~
In file included from Marlin\src\feature\drlcd\drlcd.h:6,
                 from Marlin\src\feature\drlcd\drlcd.cpp:1:
.pio\libdeps\STM32F103RC_btt\Adafruit TSL2561/Adafruit_TSL2561_U.h:190:11: warning: 'boolean' is deprecated [-Wdeprecated-declarations]
  190 |   boolean _tsl2561AutoGain;
      |           ^~~~~~~~~~~~~~~~
In file included from C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/wiring.h:34,
                 from C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/Arduino.h:36,
                 from C:\Users\Admin\.platformio\packages\framework-arduinoststm32\libraries\Wire\src/Wire.h:26,
                 from Marlin\src\feature\drlcd\drlcd.h:4,
                 from Marlin\src\feature\drlcd\drlcd.cpp:1:
C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/wiring_constants.h:110:14: note: declared here
  110 | typedef bool boolean __attribute__((deprecated));
      |              ^~~~~~~
In file included from Marlin\src\feature\drlcd\drlcd.cpp:1:
Marlin\src\feature\drlcd\drlcd.h:13:29: error: 'PIN_SENSOR_SDA' was not declared in this scope
   13 |     TwoWire _wire = TwoWire(PIN_SENSOR_SDA, PIN_SENSOR_SCL);
      |                             ^~~~~~~~~~~~~~
Marlin\src\feature\drlcd\drlcd.h:13:45: error: 'PIN_SENSOR_SCL' was not declared in this scope
   13 |     TwoWire _wire = TwoWire(PIN_SENSOR_SDA, PIN_SENSOR_SCL);
      |                                             ^~~~~~~~~~~~~~
*** [.pio\build\STM32F103RC_btt\src\src\feature\drlcd\drlcd.cpp.o] Error 1
In file included from Marlin\src\feature/drlcd/drlcd.h:6,
                 from Marlin\src\MarlinCore.cpp:256:
.pio\libdeps\STM32F103RC_btt\Adafruit TSL2561/Adafruit_TSL2561_U.h:170:21: warning: 'boolean' is deprecated [-Wdeprecated-declarations]
  170 |   boolean begin(void);
      |                     ^
In file included from C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/wiring.h:34,
                 from C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/Arduino.h:36,
                 from Marlin\src\inc/../HAL/./STM32/../shared/Marduino.h:36,
                 from Marlin\src\inc/../HAL/./STM32/HAL.h:28,
                 from Marlin\src\inc/../HAL/HAL.h:30,
                 from Marlin\src\inc/MarlinConfig.h:31,
                 from Marlin\src\MarlinCore.h:24,
                 from Marlin\src\MarlinCore.cpp:31:
C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/wiring_constants.h:110:14: note: declared here
  110 | typedef bool boolean __attribute__((deprecated));
      |              ^~~~~~~
In file included from Marlin\src\feature/drlcd/drlcd.h:6,
                 from Marlin\src\MarlinCore.cpp:256:
.pio\libdeps\STM32F103RC_btt\Adafruit TSL2561/Adafruit_TSL2561_U.h:171:33: warning: 'boolean' is deprecated [-Wdeprecated-declarations]
  171 |   boolean begin(TwoWire *theWire);
      |                                 ^
In file included from C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/wiring.h:34,
                 from C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/Arduino.h:36,
                 from Marlin\src\inc/../HAL/./STM32/../shared/Marduino.h:36,
                 from Marlin\src\inc/../HAL/./STM32/HAL.h:28,
                 from Marlin\src\inc/../HAL/HAL.h:30,
                 from Marlin\src\inc/MarlinConfig.h:31,
                 from Marlin\src\MarlinCore.h:24,
                 from Marlin\src\MarlinCore.cpp:31:
C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/wiring_constants.h:110:14: note: declared here
  110 | typedef bool boolean __attribute__((deprecated));
      |              ^~~~~~~
In file included from Marlin\src\feature/drlcd/drlcd.h:6,
                 from Marlin\src\MarlinCore.cpp:256:
.pio\libdeps\STM32F103RC_btt\Adafruit TSL2561/Adafruit_TSL2561_U.h:172:16: warning: 'boolean' is deprecated [-Wdeprecated-declarations]
  172 |   boolean init();
      |                ^
In file included from C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/wiring.h:34,
                 from C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/Arduino.h:36,
                 from Marlin\src\inc/../HAL/./STM32/../shared/Marduino.h:36,
                 from Marlin\src\inc/../HAL/./STM32/HAL.h:28,
                 from Marlin\src\inc/../HAL/HAL.h:30,
                 from Marlin\src\inc/MarlinConfig.h:31,
                 from Marlin\src\MarlinCore.h:24,
                 from Marlin\src\MarlinCore.cpp:31:
C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/wiring_constants.h:110:14: note: declared here
  110 | typedef bool boolean __attribute__((deprecated));
      |              ^~~~~~~
In file included from Marlin\src\feature/drlcd/drlcd.h:6,
                 from Marlin\src\MarlinCore.cpp:256:
.pio\libdeps\STM32F103RC_btt\Adafruit TSL2561/Adafruit_TSL2561_U.h:189:11: warning: 'boolean' is deprecated [-Wdeprecated-declarations]
  189 |   boolean _tsl2561Initialised;
      |           ^~~~~~~~~~~~~~~~~~~
In file included from C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/wiring.h:34,
                 from C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/Arduino.h:36,
                 from Marlin\src\inc/../HAL/./STM32/../shared/Marduino.h:36,
                 from Marlin\src\inc/../HAL/./STM32/HAL.h:28,
                 from Marlin\src\inc/../HAL/HAL.h:30,
                 from Marlin\src\inc/MarlinConfig.h:31,
                 from Marlin\src\MarlinCore.h:24,
                 from Marlin\src\MarlinCore.cpp:31:
C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/wiring_constants.h:110:14: note: declared here
  110 | typedef bool boolean __attribute__((deprecated));
      |              ^~~~~~~
In file included from Marlin\src\feature/drlcd/drlcd.h:6,
                 from Marlin\src\MarlinCore.cpp:256:
.pio\libdeps\STM32F103RC_btt\Adafruit TSL2561/Adafruit_TSL2561_U.h:190:11: warning: 'boolean' is deprecated [-Wdeprecated-declarations]
  190 |   boolean _tsl2561AutoGain;
      |           ^~~~~~~~~~~~~~~~
In file included from C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/wiring.h:34,
                 from C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/Arduino.h:36,
                 from Marlin\src\inc/../HAL/./STM32/../shared/Marduino.h:36,
                 from Marlin\src\inc/../HAL/./STM32/HAL.h:28,
                 from Marlin\src\inc/../HAL/HAL.h:30,
                 from Marlin\src\inc/MarlinConfig.h:31,
                 from Marlin\src\MarlinCore.h:24,
                 from Marlin\src\MarlinCore.cpp:31:
C:\Users\Admin\.platformio\packages\framework-arduinoststm32\cores\arduino/wiring_constants.h:110:14: note: declared here
  110 | typedef bool boolean __attribute__((deprecated));
      |              ^~~~~~~
In file included from Marlin\src\MarlinCore.cpp:256:
Marlin\src\feature/drlcd/drlcd.h:13:29: error: 'PIN_SENSOR_SDA' was not declared in this scope
   13 |     TwoWire _wire = TwoWire(PIN_SENSOR_SDA, PIN_SENSOR_SCL);
      |                             ^~~~~~~~~~~~~~
Marlin\src\feature/drlcd/drlcd.h:13:45: error: 'PIN_SENSOR_SCL' was not declared in this scope
   13 |     TwoWire _wire = TwoWire(PIN_SENSOR_SDA, PIN_SENSOR_SCL);
      |                                             ^~~~~~~~~~~~~~
*** [.pio\build\STM32F103RC_btt\src\src\MarlinCore.cpp.o] Error 1
========================================================================================= [FAILED] Took 24.26 seconds =========================================================================================

Environment      Status    Duration
---------------  --------  ------------
STM32F103RC_btt  FAILED    00:00:24.263
==================================================================================== 1 failed, 0 succeeded in 00:00:24.263 ====

**Comment by yofizane** [comment]
and which pin do u use for the "SDA"&"SCL" in the btt skr mini e3 v2.
![btt e3 v2](https://github.com/yaqwsx/DrLCD/assets/102444988/82d7ecc1-1fc8-4d93-b171-1f7ec1f45987)

**Comment by yaqwsx** [comment]
The error you observe:
```
Marlin\src\feature/drlcd/drlcd.h:13:29: error: 'PIN_SENSOR_SDA' was not declared in this scope
13 | TwoWire _wire = TwoWire(PIN_SENSOR_SDA, PIN_SENSOR_SCL);
| ^~~~~~~~~~~~~~
Marlin\src\feature/drlcd/drlcd.h:13:45: error: 'PIN_SENSOR_SCL' was not declared in this scope
13 | TwoWire _wire = TwoWire(PIN_SENSOR_SDA, PIN_SENSOR_SCL);
```

is caused by the fact that these constants are only available in the environment `STM32F103RC_btt_drlcd` - which is the environment intended for the build. The SDA and SCL pins are PB8 and PB9 on the EXP1 connector.
