### ISSUE TITLE
failed to acquire data

### ISSUE THREAD

**Issue by yofizane** [yaqwsx/DrLCD#3]
Hello yaqwsx,I have complied the firmware.bin and upload to btt skr mini e3 v2 board,I wired the sda scl gnd and vcc as your picture,but it doesnt acuquire lumina data ,it shows as below:

root@NanoPC-T6:~# drlcd measurelcd --size 100x50 --resolution 100x50 --fast mars4ultra.json
Row 1 / 50, 0.5
Warning, some samples were missing; retrying
Warning, some samples were missing; retrying
Warning, some samples were missing; retrying
Warning, some samples were missing; retrying
Warning, some samples were missing; retrying
Warning, some samples were missing; retrying
Warning, some samples were missing; retrying
Warning, some samples were missing; retrying
Warning, some samples were missing; retrying

I tested M5500 gcode in the vscode as below
M5500
11:37:29.826 > Data: 65536.00
11:37:29.826 > ok

perhaps the tsl2561 sensor was broken?or I made a misktake in someware?

**Comment by yaqwsx** [comment]
The sensor is I2C. Reading 65536 means it didn't output any data, and the MCU real all ones - the line stayed high. 
There can be a couple of reasons:
- wrong connection (be sure it matches the definition in the code: https://github.com/yaqwsx/DrLCD/blob/a6063b4c4d11f1b6ee0c002ea18fec031ed11072/fw/buildroot/share/PlatformIO/variants/MARLIN_F103Rx_DRLCD/variant.h#L144C1-L145),
- if you have really long wires it is possible that you have weak pull-up resistors on the SDA and SCL lines.
-  I wouldn't suspect the sensor to be broken.

**Comment by yofizane** [comment]
still failed to get the data,I even bought a new e3 v2 board & a new tsl2561,now with "drlcd measurelcd" command,it can collect data,but all with 65536,perhaps there is something wrong with the firmware I compiled?I only changed "default_envs = STM32F103RC_btt_drlcd" in the platformio.ini,it successfully complied a firmware,and I upload the firmware with sd card,the M5500 gcode can be send in the serial console,but all with 65536,my wire is as blow 
![IMG_20240712_205044](https://github.com/user-attachments/assets/ff3b0a3e-6919-4877-b410-5805509a2e4b)
![IMG_20240712_205100](https://github.com/user-attachments/assets/9a9def88-0d0b-42f1-b577-0f3bfc8b389f)

**Comment by yofizane** [comment]
yes,u are right,the sensor is not broken(I connect sensor to ramps1.4,and upload a simple program,it has normal output,not 65536),
I also changed "boolean" to "bool" in Adafruit_TSL2561_U.cpp as vscode shows "warning: 'boolean' is deprecated",but on skr mini e3 v2,the output is still 65536,so frustrated.
is there anything I missed in compling the fw?the wire is simple, only 4 wire,I dont think I connected wrong,or any  DIAG jumpers need plug in or plug out?

**Comment by yaqwsx** [comment]
Can you examine the communication with a logic analyzer or oscilloscope?

**Comment by yofizane** [comment]
sorry,I cant,I'm just an amateur，cloud you give me a copy of the firmware you compiled?

**Comment by yaqwsx** [comment]
[firmware.zip](https://github.com/user-attachments/files/16253188/firmware.zip)

**Comment by yofizane** [comment]
your fw also  doesn't work,then I changed   
<_**Adafruit_TSL2561_Unified _tsl2561 = Adafruit_TSL2561_Unified(TSL2561_ADDR_HIGH);**_> to <**_Adafruit_TSL2561_Unified _tsl2561 = Adafruit_TSL2561_Unified(TSL2561_ADDR_FLOAT, 12345);_**> in the drlcd.h,it finally got the real density not 65536
will the change I made cause problems in scanning?

**Comment by yaqwsx** [comment]
The module has a configurable I2C address. It seems that the module you bought simply has a different address configured as default. The change you made is totally fine.

**Comment by yofizane** [comment]
well,there is somthing strange,after several lines measurement,the output stay a same result until I reboot skr mini e3 v2,maybe still because of  the module?

the result is like this
root@NanoPC-T6:~# drlcd measurelcd --size 50x30 --resolution 50x30 --fast test.json
Row 1 / 30, 0.5
Measurement unsuccessful, lowering feedrate to 2850.0
Measurement unsuccessful, lowering feedrate to 2707.5
  Got [2912.0, 2926.0, 2940.0, 2940.0, 2926.0, 2926.0, 2912.0, 2912.0, 2912.0, 2912.0, 2912.0, 2897.0, 2869.0, 2869.0, 2897.0, 2867.0, 2825.0, 2810.0, 2796.0, 2782.0, 2768.0, 2768.0, 2768.0, 2782.0, 2796.0, 2796.0, 2796.0, 2782.0, 2782.0, 2782.0, 2796.0, 2796.0, 2796.0, 2810.0, 2810.0, 2810.0, 2825.0, 2825.0, 2839.0, 2839.0, 2839.0, 2839.0, 2839.0, 2839.0, 2839.0, 2839.0, 2839.0, 2839.0, 2839.0, 2839.0]
Row 2 / 30, 1.5
  Got [2839.0, 2839.0, 2839.0, 2853.0, 2867.0, 2882.0, 2882.0, 2896.0, 2912.0, 2926.0, 2940.0, 2954.0, 2954.0, 2940.0, 2940.0, 2926.0, 2897.0, 2883.0, 2883.0, 2855.0, 2826.0, 2798.0, 2783.0, 2796.0, 2796.0, 2796.0, 2796.0, 2796.0, 2796.0, 2810.0, 2810.0, 2810.0, 2825.0, 2839.0, 2853.0, 2839.0, 2839.0, 2839.0, 2839.0, 2839.0, 2839.0, 2839.0, 2839.0, 2839.0, 2839.0, 2839.0, 2839.0, 2839.0, 2839.0, 2839.0]
Row 3 / 30, 2.5
  Got [2768.0, 2782.0, 2782.0, 2782.0, 2768.0, 2782.0, 2768.0, 2782.0, 2768.0, 2768.0, 2768.0, 2768.0, 2768.0, 2768.0, 2768.0, 2768.0, 2768.0, 2768.0, 2768.0, 2753.0, 2753.0, 2753.0, 2753.0, 2753.0, 2753.0, 2753.0, 2753.0, 2753.0, 2753.0, 2753.0, 2753.0, 2753.0, 2753.0, 2753.0, 2753.0, 2753.0, 2753.0, 2753.0, 2739.0, 2753.0, 2753.0, 2739.0, 2739.0, 2739.0, 2739.0, 2739.0, 2739.0, 2739.0, 2739.0, 2739.0]
Row 4 / 30, 3.5
  Got [2796.0, 2796.0, 2810.0, 2810.0, 2810.0, 2810.0, 2810.0, 2810.0, 2810.0, 2810.0, 1.0, 2810.0, 2810.0, 2810.0, 2810.0, 2810.0, 2810.0, 2810.0, 2810.0, 2810.0, 2810.0, 2810.0, 2810.0, 2810.0, 2810.0, 2810.0, 2810.0, 2810.0, 2810.0, 2810.0, 2810.0, 2810.0, 2810.0, 2810.0, 2810.0, 2796.0, 2782.0, 2768.0, 2768.0, 2753.0, 2753.0, 2753.0, 2753.0, 2753.0, 2753.0, 2753.0, 2753.0, 2753.0, 2753.0, 2753.0]
Row 5 / 30, 4.5
  Got [2768.0, 2768.0, 2768.0, 2753.0, 2753.0, 2753.0, 2753.0, 2753.0, 2753.0, 2753.0, 2739.0, 2739.0, 2739.0, 2725.0, 2725.0, 2711.0, 2711.0, 2711.0, 2697.0, 2711.0, 2697.0, 2711.0, 2697.0, 2711.0, 2711.0, 2725.0, 2725.0, 2725.0, 2725.0, 2725.0, 2739.0, 2725.0, 2725.0, 2725.0, 2739.0, 2739.0, 2739.0, 2739.0, 2739.0, 2739.0, 2739.0, 2725.0, 2739.0, 2725.0, 2739.0, 2725.0, 2725.0, 2725.0, 2725.0, 2711.0]
Row 6 / 30, 5.5
  Got [2768.0, 2768.0, 2768.0, 2768.0, 2782.0, 2782.0, 2782.0, 2782.0, 2782.0, 2782.0, 2782.0, 2782.0, 2782.0, 2782.0, 2782.0, 2768.0, 2768.0, 2768.0, 2768.0, 2768.0, 2768.0, 2768.0, 2768.0, 2768.0, 2768.0, 2768.0, 2768.0, 2768.0, 2768.0, 2768.0, 2768.0, 2782.0, 2782.0, 2782.0, 2768.0, 2768.0, 2768.0, 2768.0, 2768.0, 2782.0, 2768.0, 2768.0, 2768.0, 2768.0, 2753.0, 2753.0, 2753.0, 2753.0, 2739.0, 2739.0]
Row 7 / 30, 6.5
  Got [2711.0, 2711.0, 2697.0, 2697.0, 2697.0, 2697.0, 2711.0, 2711.0, 2725.0, 2697.0, 2711.0, 2725.0, 2753.0, 2768.0, 2782.0, 2796.0, 2782.0, 2782.0, 2768.0, 2768.0, 2753.0, 2753.0, 2739.0, 2739.0, 2739.0, 2739.0, 2739.0, 2739.0, 2725.0, 2725.0, 2725.0, 2725.0, 2711.0, 2725.0, 2725.0, 2711.0, 2725.0, 2711.0, 2711.0, 2697.0, 2697.0, 2697.0, 2697.0, 2697.0, 2697.0, 2697.0, 2697.0, 2697.0, 2697.0, 2697.0]
Row 8 / 30, 7.5
Measurement unsuccessful, lowering feedrate to 2572.1249999999995
  Got [34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0]
Row 9 / 30, 8.5
  Got [34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0]
Row 10 / 30, 9.5
  Got [34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0]
Row 11 / 30, 10.5
  Got [34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0]
Row 12 / 30, 11.5
  Got [34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0]
Row 13 / 30, 12.5
  Got [34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0]
Row 14 / 30, 13.5
  Got [34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0]
Row 15 / 30, 14.5
  Got [34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0]
Row 16 / 30, 15.5
  Got [34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0]
Row 17 / 30, 16.5
^C
Aborted!

**Comment by yofizane** [comment]
finally,I solve the problem,thank u
